
[origins]

	[origins."origins:shulk"]
		"origins:strong_arms" = true
		"origins:no_shield" = true
		"origins:more_exhaustion" = true
		"origins:strong_arms_break_speed" = true
		"origins:natural_armor" = true
		enabled = true
		"origins:shulker_inventory" = true

	[origins."origins:merling"]
		"origins:air_from_potions" = true
		"origins:swim_speed" = true
		"origins:water_vision" = true
		"origins:like_water" = true
		"origins:aqua_affinity" = true
		"origins:water_breathing" = true
		"origins:conduit_power_on_land" = true
		enabled = true
		"origins:aquatic" = true

	[origins."origins:arachnid"]
		"origins:carnivore" = true
		"origins:fragile" = true
		"origins:arthropod" = true
		"origins:master_of_webs" = true
		enabled = true
		"origins:climbing" = true

	[origins."origins:phantom"]
		"origins:phasing" = true
		"origins:fragile" = true
		"origins:phantomize" = true
		"origins:translucent" = true
		"origins:invisibility" = true
		"origins:hunger_over_time" = true
		enabled = true
		"origins:burn_in_daylight" = true
		"origins:phantomize_overlay" = true

	[origins."origins:enderian"]
		"origins:water_vulnerability" = true
		"origins:throw_ender_pearl" = true
		"origins:pumpkin_hate" = true
		"origins:ender_particles" = true
		"origins:damage_from_potions" = true
		enabled = true
		"origins:extra_reach" = true

	[origins."origins:blazeborn"]
		"origins:water_vulnerability" = true
		"origins:flame_particles" = true
		"origins:burning_wrath" = true
		"origins:hotblooded" = true
		"origins:fire_immunity" = true
		"origins:damage_from_snowballs" = true
		"origins:nether_spawn" = true
		"origins:damage_from_potions" = true
		enabled = true

	[origins."origins:feline"]
		"origins:cat_vision" = true
		"origins:velvet_paws" = true
		"origins:fall_immunity" = true
		"origins:weak_arms" = true
		"origins:nine_lives" = true
		enabled = true
		"origins:sprint_jump" = true
		"origins:scare_creepers" = true

	[origins."origins:elytrian"]
		"origins:more_kinetic_damage" = true
		"origins:elytra" = true
		"origins:claustrophobia" = true
		"origins:aerial_combatant" = true
		"origins:light_armor" = true
		"origins:launch_into_air" = true
		enabled = true

	[origins."origins:human"]
		enabled = true

	[origins."origins:avian"]
		"origins:fresh_air" = true
		"origins:vegetarian" = true
		"origins:lay_eggs" = true
		"origins:slow_falling" = true
		"origins:tailwind" = true
		"origins:like_air" = true
		enabled = true

	[origins."mrt_supports:alpha2"]
		enabled = true
		"mrt_supports:alpha2/crafting" = true
		"mrt_supports:alpha2/storage" = true
		"mrt_supports:alpha2/smelt" = true
		"mrt_supports:alpha2/scan-ores" = true
		"mrt_supports:alpha2/battery" = true
		"mrt_supports:alpha2/solarpanel" = true
		"mrt_supports:alpha2/redstone" = true
		"mrt_supports:alpha2/self-repair" = true
		"mrt_supports:alpha2/compact" = true
		"mrt_supports:alpha2/machine-like" = true
		"mrt_supports:alpha2/short-circuit" = true
		"mrt_supports:alpha2/power-saving" = true
		"mrt_supports:alpha2/iron-clad" = true

	[origins."origins_gender:male"]
		enabled = true
		"origins_gender:male" = true

	[origins."origins_gender:female"]
		enabled = true
		"origins_gender:female" = true

	[origins."mrt_supports:groved"]
		enabled = true
		"mrt_supports:groved/natures-embrace" = true
		"mrt_supports:groved/life-blessing" = true
		"mrt_supports:groved/photosynthesis" = true
		"mrt_supports:groved/leaf-fragile" = true
		"origins:vegetarian" = true

	[origins."mrt_supports:soulweaver"]
		enabled = true
		"mrt_supports:soulweaver/assignid" = true
		"mrt_supports:soulweaver/soullink" = true
		"mrt_supports:soulweaver/teleport" = true
		"mrt_supports:soulweaver/cleanse" = true
		"mrt_supports:soulweaver/veil-beyond" = true
		"mrt_supports:soulweaver/echo-sight" = true
		"mrt_supports:soulweaver/unwoven" = true
		"mrt_supports:soulweaver/light-soul" = true
		"origins:no_shield" = true
		"mrt_supports:soulweaver/fragmented-shell" = true
		"mrt_supports:soulweaver/no-rest" = true
		"mrt_supports:soulweaver/see-health" = true
		"mrt_supports:soulweaver/selector" = true

	[origins."aetherborn:aetherborn"]
		enabled = true
		"origins:fall_immunity" = true
		"origins:elytra" = true
		"origins:claustrophobia" = true
		"origins:aerial_combatant" = true
		"origins:fresh_air" = true
		"origins:tailwind" = true
		"origins:more_exhaustion" = true
		"aetherborn:aether_armor_only" = true
		"aetherborn:spawn_in_aether" = true
		"aetherborn:fast_flying" = true
		"aetherborn:aether_tools_only" = true
		"origins:launch_into_air" = true
		"aetherborn:extreme_hunger" = true
		"aetherborn:aetherian_diet" = true
		"aetherborn:launch_into_air" = true
		"origins:weak_arms" = true
		"aetherborn:weak_on_ground" = true
		"aetherborn:low_defense" = true

