
[common]

	#Properties relating to gameplay
	[common.gameplay]
		#If true, enables the draw animation for weapons
		drawAnimation = true
		#Multiplier to adjust the capacity of all ammo boxes.
		#Range: 0.1 ~ 100.0
		ammoBoxCapacityMultiplier = 1.0
		#If true, guns will be damageable and can break, coward if you toggle this
		enableGunDamage = true
		#If true, gun attachments will be damageable and can break, also a coward
		enableAttachmentDamage = true
		#The extra amount to expand an entity's bounding box when checking for projectile collision. Setting this value higher will make it easier to hit entities
		#Range: 0.0 ~ 1.0
		growBoundingBoxAmount = 0.3
		#Enables the check for head shots for players. Projectiles that hit the head of a player will have increased damage.
		enableHeadShots = true
		#The value to multiply the damage by if projectile hit the players head
		#Range: 1.0 ~ 1.7976931348623157E308
		headShotDamageMultiplier = 1.25
		#The value to multiply the damage by if projectile is a critical hit
		#Range: 1.0 ~ 1.7976931348623157E308
		criticalDamageMultiplier = 1.5
		#If true, projectiles will ignore leaves when checking for collision
		ignoreLeaves = true
		#If true, projectiles will cause knockback when an entity is hit. By default this is set to true to match the behaviour of Minecraft.
		enableKnockback = true
		#Sets the strength of knockback when shot by a bullet projectile. Knockback must be enabled for this to take effect. If value is equal to zero, knockback will use default minecraft value
		#Range: 0.0 ~ 1.0
		knockbackStrength = 0.15
		#If true, improves the accuracy of weapons by considering the ping of the player. This has no affect on singleplayer. This will add a little overhead if enabled.
		improvedHitboxes = false
		#Damage dealt by the Enemy Guns
		#Range: 0.0 ~ 1.7976931348623157E308
		enemyBulletDamage = 4.5
		#Energy produced per tick by the Polar Generator. Adjust this value to balance the generator's output.
		#Range: > 1
		energyProductionRate = 50
		#If true, guns will always use energy system even if Create mod is loaded NOT WORKING.
		forceEnergyGuns = false
		#If true, guns will toggle ADS mode.
		toggleADS = false

		#Properties related to gun griefing
		[common.gameplay.griefing]
			#If enabled, allows block removal on explosions
			enableBlockRemovalOnExplosions = true
			#If enabled, allows guns to shoot out glass and other fragile objects
			enableGlassBreaking = true
			#If enabled, fragile blocks will drop their loot when broken
			fragileBlockDrops = true
			#The base chance that a fragile block is broken when impacted by a bullet. The hardness of a block will scale this value; the harder the block, the lower the final calculated chance will be.
			#Range: 0.0 ~ 1.0
			fragileBlockBreakChance = 1.0
			#If true, allows guns enchanted with Fire Starter to light and spread fires on blocks
			setFireToBlocks = true
			#If true, allows heavy rounds to break blocks
			enableBlockBreaking = true
			#If true, allows beam weapons to mine blocks
			enableBeamMining = true

		[common.gameplay.gameplay]
			#Set to false to disable the spawning of casing items when firing guns.
			spawnCasings = true

	#Properties relating to network
	[common.network]
		#The distance players need to be within to be able to track new projectiles trails. Higher values means you can see projectiles from that start from further away.
		#Range: 1.0 ~ 1.7976931348623157E308
		projectileTrackingRange = 200.0

	#Properties relating to mob aggression
	[common.aggro_mobs]
		#If true, nearby mobs are angered and/or scared by the firing of guns.
		enabled = true
		#If true, in addition to causing peaceful mobs to panic, firing a gun will also cause nearby hostile mobs to target the shooter.
		angerHostileMobs = true
		#Any mobs within a sphere of this radius will aggro on the shooter of an unsilenced gun.
		#Range: 0.0 ~ 1.7976931348623157E308
		unsilencedRange = 20.0
		#Any mobs of defined will not aggro on shooters
		exemptMobs = []

	#Properties relating to mob fleeing
	[common.fleeing_mobs]
		#If true, nearby mobs will flee from the firing of guns.
		enabled = true
		#Any mobs within a sphere of this radius will flee from the shooter of an unsilenced gun.
		#Range: 0.0 ~ 1.7976931348623157E308
		unsilencedRange = 20.0
		#Any mobs within a sphere of this radius will flee from the shooter of a silenced gun.
		#Range: 0.0 ~ 1.7976931348623157E308
		silencedRange = 20.0
		#Any mobs listed here will flee from shooters
		fleeingEntities = ["minecraft:cow", "minecraft:sheep", "minecraft:pig", "minecraft:chicken", "minecraft:rabbit", "minecraft:horse", "minecraft:villager"]

	#Properties relating to projectile spread
	[common.projectile_spread]
		#The amount of time in milliseconds before logic to apply spread is skipped. The value indicates a reasonable amount of time before a weapon is considered stable again.
		#Range: 0 ~ 1000
		spreadThreshold = 300
		#The amount of times a player has to shoot within the spread threshold before the maximum amount of spread is applied. Setting the value higher means it will take longer for the spread to be applied.
		#Range: > 1
		maxCount = 10

