
#Client-only settings
[client]
	#Displays the full tooltip when hovering over an item in the tool belt. If false, only the item name is shown
	showTooltip = false
	#Overlay X offset (positive value moves right, negative moves left)
	#Range: > -2147483648
	offsetX = 0
	#Overlay Y offset (positive value moves down, negative moves up)
	#Range: > -2147483648
	offsetY = 0

